### ISSUE TITLE
Error use_nesterov

### ISSUE THREAD

**Issue by nassarofficial** [ardiya/siamesenetwork-tensorflow#1]
I got this error while trying to train.
>   File "train.py", line 40, in <module>
>     train_step = tf.train.MomentumOptimizer(0.01, 0.99, use_nesterov=True).minimize(loss, global_step=global_step)
> TypeError: __init__() got an unexpected keyword argument 'use_nesterov'
>

**Comment by ardiya** [comment]
you need to update tensorflow to r0.10 or newer in order to use nesterov momentum.
https://www.tensorflow.org/versions/r0.10/api_docs/python/train.html#MomentumOptimizer

**Comment by nassarofficial** [comment]
Thank you, this turned out to be the issue!
