### ISSUE TITLE
Why an extra axis is added in dataset.py for class MNISTDataset

### ISSUE THREAD

**Issue by Shameendra** [ardiya/siamesenetwork-tensorflow#12]
Hi ,
i have a question regarding the dataset,py. I am trying to create my own dataset to test the model and in the dataset.py in 

    class MNISTDataset(Dataset):
        def __init__(self):
		print("===Loading MNIST Dataset===")
		(self.images_train, self.labels_train), (self.images_test, self.labels_test) = mnist.load_data()
		self.images_train = np.expand_dims(self.images_train, axis=3) / 255.0
		self.images_test = np.expand_dims(self.images_test, axis=3) / 255.0

Can anyone explain why we are adding a new axis? I am trying to create a dataset witg RGB channels. And i dont know if the MNIST dataset is in grayscale?

**Comment by ardiya** [comment]
The goal is to convert it to NHWC (`num_data`, `image_height`, `image_width`, `channel_size`). [see `data_format` in `tf.contrib.layers.conv2d` for reference](https://www.tensorflow.org/api_docs/python/tf/contrib/layers/conv2d).

The mnist dataset is grayscale, from 0-255. The shape of `self.images_train` should be (num_data, 28, 28).
The shape of `np.expand_dims(self.images_train, axis=3)` would be (num_data, 28, 28, 1).

If you already have an RGB image you wouldn't need to add extra dimension in the end.
